name: 'Commit Message Check'
on:
  push:
    branches:
      - main

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check for Commit Type
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '(fix|feat|chore|refactor)[:](.+)'
          error: 'Commit message should look like: <category>: <description>, where category is one of: fix, feat, chore, refactor.'
